version: '3.4'

services:
  tenantsdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  saas.api:
    image: ${DOCKER_REGISTRY-}saas
    build:
      context: .
      dockerfile: SaaS.Api/Dockerfile
